Scheduling a maintenance window — with the actual names
Support person submits the booking → POST /v1/maintenance-events on the facade (routers mounted in the host app fdn-c-amp-fapis-py). Body: startTime, endTime, ticketNumber, reason. Headers: X-Client-Id (required), Idempotency-Key (recommended, a UUID), X-Correlation-Id (optional). Handler: schedule_event in routes/zelle/events.py.
Name-tag check → the require_client_id dependency validates X-Client-Id against ZELLE_CLIENT_ALLOWLIST. Missing → 400 VALIDATION_FAILED; not on the list → 403 FORBIDDEN_ACTION.
Sanity checks → EventService.schedule in event_service.py: pydantic window validation (422 on bad input), overlap check against existing rows in the zelle_events collection, and — if an Idempotency-Key was sent — a ledger row in zelle_idempotency (unique on client_id + key; a replay returns the stored response instead of continuing).
Logbook, before anything is sent → an INTENT document into zelle_audit (kind: "INTENT", action: "schedule", attempt_id, actor_client_id, correlation_id) — the pair you saw in Compass.
Sign in to Zelle → TokenBroker in token_broker.py signs an RS256 client assertion (private key at ZELLE_SIGNING_KEY_PATH, key id ZELLE_SIGNING_KID) and POSTs it to the token endpoint — CAT https://auth.zelle.cat.earlywarning.io/token, PROD https://auth.zelle.earlywarning.com/token — with aud = CAT https://auth-zelle.cat.earlywarning.io/oauth2/access/v1/token / PROD https://auth-zelle.earlywarning.com/oauth2/access/v1/token and scope maintenance-event. The access token is cached (~30 min) and reused across calls.
Send the booking → ZomsClient.schedule in zoms_client.py → POST https://api.zelle.cat.earlywarning.io/zoms/v1/events/schedule (PROD: api.zelle.earlywarning.com). Headers: Authorization: Bearer …, request-id (fresh UUID per attempt), idempotency-id (the facade-minted UUID stored on the event). Body: orgId, participantName, submittedName, contactName/Phone/Email auto-filled from ZELLE_ORG_ID / ZELLE_CONTACT_* config, plus the window as scheduledStartDate/scheduledEndDate and ewsHold.
Zelle's answer recorded → the 201 body's maintenanceEventId is stored as ews_event_id on the zelle_events document; an OUTCOME document (same attempt_id) goes into zelle_audit; event status → SCHEDULED. If Zelle accepted but returned no id: status PENDING_UPSTREAM_ID and the caller sees 202 instead of 201.
Receipt to the caller → JSON with eventId (ours — the handle for everything after), status, ticketNumber, the window, and correlationId (also echoed in the X-Correlation-Id response header).
Any failure → one envelope shape: {"error": {"code", "message", "correlationId", "retryable"}} with codes from the fixed list (VALIDATION_FAILED, CONFLICT, FORBIDDEN_ACTION, NOT_FOUND, UPSTREAM_REJECTED, UPSTREAM_UNAVAILABLE, RATE_LIMITED, UPSTREAM_UNCERTAIN), the event lands FAILED (clean rejection) or UNCERTAIN (ambiguous outcome — locked for an operator), and the zelle_audit OUTCOME row records why.


Looking up an event — with the actual names
By id → GET /v1/maintenance-events/{eventId}; the list → GET /v1/maintenance-events?status=SCHEDULED (filter optional). Header: X-Client-Id.
Answered from our own records → EventService.get_event / list_events read the zelle_events collection in the Mongo database fdn-c-amp-fapis-py. No call to Zelle, no token involved — instant.
The status values you can see: PENDING, PENDING_UPSTREAM_ID, SCHEDULED, IN_PROGRESS, COMPLETE, CANCELLED, UNCERTAIN, FAILED.
Live check at the source → GET /v1/maintenance-events/{eventId}/upstream-status → ZomsClient.get_status → GET https://api.zelle.cat.earlywarning.io/zoms/v1/events/{maintenanceEventId} (real call, needs the token from step 5 above). Returns localStatus and upstreamStatus side by side plus checkedAt; 409 if the event has no ews_event_id yet.
