{
  "distinguished_name": "171384.boss.dev",
  "start_date": "null",
  "expiration_date": {
    "$date": "2027-03-11T00:00:00.000Z"
  },
  "csi_application_id": 171384,
  "status": "Valid",
  "days_to_expiration": 546,
  "source_properties": {
    "name": "HashiCorp",
    "serial_number": "690002ee5bd989e475c9d4e3fa00000002ee5b",
    "certificate_type": "jks",
    "certificate_owner": "null",
    "certificate_name": "null",
    "owner_email": "null",
    "support_group": "null",
    "support_group_email": "null",
    "application_manager": "null",
    "l3_application_head": "null",
    "l4_application_head": "null",
    "environment": "DEV",
    "evolven_host": "null",
    "evolven_path": "null",
    "ssg_domain": "null",
    "ssg_url_in": "null",
    "ssg_url_out": "null",
    "internal_ssg_domain": "null",
    "ssg_url": "null",
    "san_names": "null",
    "instance_name": "N/A",
    "microservice_name": "namcgbgtd25d_gcb-nam-wmt-retail-171384_gtlecsdev3-pdm-o-accountlinking-usretail",
    "openshift_namespace": "null",
    "openshift_container": "null",
    "ssl_cm_region": "NAM",
    "ssl_cm_sector": "PBWM",
    "ssl_cm_status": "null",
    "lob_domain": "NAM_Core",
    "TechnologyManagedSegment_L6": "USPB Technology [L6]",
    "TechnologyManagedSegment_L7": "Digital [L7]",
    "ApplicationManager": "XXXXXX",
    "ApplicationManager_soEid": "XXXXXX",
    "Level3Head": "XXXXXX",
    "Level4Head": "XXXXXX",
    "Level5Head": "XXXXXX",
    "SupportManager": "XXXXXX",
    "Domain": "NAM_Core",
    "SubDomain": "Assisted Channels",
    "LOB": "RETAIL"
  },
  "log_date": {
    "$date": "2025-09-10T06:33:13.311Z"
  }
}